name: Run ESLint on manual trigger

on:
  workflow_dispatch: # Triggered manually

jobs:
  lint:
    runs-on: ubuntu-latest

    container:
      image: node:20

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        path: . # Specify the path where the repository should be checked out

    - name: Override npm registry
      run: npm config set registry https://registry.npmjs.org/
      
    - name: Install dependencies
      run: npm install eslint  

    
