name: Run ESLint on manual trigger

on:
  workflow_dispatch: # Triggered manually

jobs:
  lint:
    runs-on: ubuntu-latest

    container:
      image: node:20

    steps:
    - name: Install dependencies
      run: npm install

    - name: Run ESLint
      run: npm run lint
